// 태그 네이밍 규칙 및 정규화 모듈
// 기준: tag-review 스킬 v8 (2026-03-23) — 투자 메모 DB Topic/Company 기준 태그 목록 + 네이밍 규칙(A~E)
//
// 사용처: AI가 Topic/Company 태그를 자동 배정하는 모든 지점
//  1) 프롬프트에 TAG_RULES_PROMPT 를 삽입해 LLM에 규칙을 지시
//  2) LLM 응답을 normalizeTopics / normalizeCompanies 로 저장 직전에 강제 정규화

// ─────────────────────────────────────────────
// 기준 Company 태그 목록 (v8, 265개)
// ─────────────────────────────────────────────
export const CANONICAL_COMPANIES = [
  "AMD",
  "Amkor",
  "ARM",
  "ASE",
  "ASML",
  "AST",
  "AST스페이스모바일",
  "ASTS",
  "AT&T",
  "BESI",
  "BHP",
  "BP",
  "BYD",
  "CATL",
  "CFS",
  "CJ",
  "CRML",
  "CXMT",
  "DELL",
  "DL",
  "E1",
  "EMC",
  "EveEnergy",
  "Fenghua",
  "FtaiAviation",
  "GE버노바",
  "GKL",
  "GST",
  "HD한국조선해양",
  "HD현대마린엔진",
  "HD현대에너지솔루션",
  "HD현대오일뱅크",
  "HD현대일렉트릭",
  "HD현대중공업",
  "HJ중공업",
  "HMM",
  "HP",
  "HPE",
  "HPSP",
  "IBM",
  "IHI중공업",
  "IMAX",
  "ISC",
  "ITEQ",
  "JENTECH",
  "JP모건",
  "KB금융",
  "KB손해보험",
  "KSS해운",
  "KYEC",
  "LG에너지솔루션",
  "LG이노텍",
  "LG전자",
  "LG화학",
  "LIG넥스원",
  "LS",
  "LS마린솔루션",
  "LS일렉트릭",
  "LS전선",
  "LX세미콘",
  "Microchip",
  "Monolithic",
  "MP머티리얼즈",
  "MPS",
  "NXP",
  "OCI",
  "OHB",
  "Panasonic",
  "POWI",
  "Renesas",
  "RFHIC",
  "Shengyi",
  "SK",
  "SK가스",
  "SK이노베이션",
  "SK텔레콤",
  "SK하이닉스",
  "SKC",
  "SMIC",
  "SNT에너지",
  "SPIL",
  "STM",
  "STX엔진",
  "TMC",
  "TSMC",
  "TUC",
  "UMC",
  "UsaRareEarth",
  "Vicor",
  "YAGEO",
  "YMTC",
  "가온전선",
  "강원랜드",
  "강원에너지",
  "고려아연",
  "구글",
  "국헌하이테크",
  "글로벌세아",
  "기아",
  "나노뉴클리어에너지",
  "나브테스코",
  "나비타스세미컨덕터",
  "난야테크놀로지",
  "남선알미늄",
  "네비우스",
  "네이버",
  "네패스아크",
  "넥스페리아",
  "넷플릭스",
  "노베온",
  "노스롭그루먼",
  "노키아",
  "농심",
  "뉴스케일파워",
  "니콘",
  "닛토보세키",
  "대덕전자",
  "대양제지",
  "대주전자재료",
  "대창솔루션",
  "대한광통신",
  "대한전선",
  "대한조선",
  "도쿄일렉트론",
  "동진쎄미캠",
  "두나무",
  "두산",
  "두산네패스",
  "두산에너빌리티",
  "두산테스나",
  "두산BG",
  "드림텍",
  "디스코",
  "디아이티",
  "디즈니",
  "딥시크",
  "라이너스",
  "라인메탈",
  "레녹스",
  "레이크머티리얼즈",
  "레인보우로보틱스",
  "레조낙",
  "로레알",
  "로보티즈",
  "로켓랩",
  "록히드마틴",
  "롯데건설",
  "롯데관광개발",
  "롯데에너지머티리얼즈",
  "롯데케미칼",
  "루멘텀",
  "루멘테크놀로지",
  "리노공업",
  "리오틴토",
  "리튬아메리카스",
  "마루베니상사",
  "마벨테크놀로지",
  "마이크로소프트",
  "마이크론",
  "마이트론",
  "메타",
  "무라타",
  "미래에셋벤처투자",
  "미래에셋증권",
  "미쓰비시상사",
  "미쓰비시중공업",
  "미쓰이물산",
  "미쓰이상사",
  "바이두",
  "바이트댄스",
  "반다이남코",
  "발레",
  "버티브홀딩스",
  "범한퓨얼셀",
  "보스턴다이내믹스",
  "브로드컴",
  "블룸에너지",
  "비츠로셀",
  "비트마인",
  "삼보판지",
  "삼성물산",
  "삼성생명",
  "삼성전기",
  "삼성전자",
  "삼성중공업",
  "삼성증권",
  "삼성화재",
  "삼성E&A",
  "삼성SDI",
  "삼성SDS",
  "삼양식품",
  "삼영엠텍",
  "샌디스크",
  "서클",
  "성광밴드",
  "성신양회",
  "세레브라스",
  "세명전기",
  "세아베스틸지주",
  "세아상역",
  "세진중공업",
  "센트러스에너지",
  "셀레스티카",
  "솔리드파워",
  "솔브레인",
  "쉘",
  "슈퍼마이크로컴퓨터",
  "스미모토케미칼",
  "스미토모상사",
  "스워머",
  "스트레티지",
  "스페이스X",
  "시구르드",
  "시놉시스",
  "시세이도",
  "신대양제지",
  "신에츠케미칼",
  "실리콘모션",
  "심텍",
  "쌍용",
  "쏠리드",
  "씨게이트",
  "아람코",
  "아리스타네트웍스",
  "아마존",
  "아세아제지",
  "아이렌",
  "아카마이",
  "알리바바",
  "알몬티",
  "알버말",
  "알코아",
  "알테오젠",
  "애플",
  "야스카와전기",
  "어플라이드디지털",
  "에릭슨",
  "에스엔시스",
  "에스엔에스텍",
  "에쓰오일",
  "에어부산",
  "에이엘티",
  "에이피알",
  "에코랩",
  "에퀴노르",
  "에프에스티",
  "엑손",
  "엔비디아",
  "엔비전파워",
  "엔알비",
  "엔트로픽",
  "영원무역홀딩스",
  "오라클",
  "오리엔탈정공",
  "오클로",
  "오픈AI",
  "옥시덴탈",
  "온다스",
  "와이엠씨",
  "우림피티에스",
  "우진",
  "원익로보틱스",
  "원익IPS",
  "웨스턴디지털",
  "유니셈",
  "유니트리",
  "유진테크",
  "이랜드",
  "이비덴",
  "이수스페셜티케미컬",
  "이수페타시스",
  "이오테크닉스",
  "이월드",
  "이토추상사",
  "이튼",
  "인테그리스",
  "인텔",
  "일라이릴리",
  "제너럴다이내믹스",
  "제주반도체",
  "조비에비에이션",
  "존슨컨트롤즈",
  "지멘스",
  "지멘스에너지",
  "진에어",
  "카메코",
  "카카오",
  "카펜터",
  "캐논",
  "캐리어",
  "컨스털레이션에너지",
  "컴포트시스템즈",
  "케이엔에스",
  "케이엔제이",
  "코그니전트",
  "코닝",
  "코어사이언티픽",
  "코어위브",
  "코오롱인더",
  "코인베이스",
  "코히어런트",
  "콴타",
  "퀀텀스케이프",
  "퀄컴",
  "크레도테크놀로지",
  "클라우드플레어",
  "키옥시아",
  "키움증권",
  "탈렌에너지",
  "태광",
  "태림페이퍼",
  "태림포장",
  "태웅",
  "테더",
  "테레스티얼에너지",
  "테스",
  "테슬라",
  "테크윙",
  "텍사스인스트루먼츠",
  "텐센트",
  "토탈에너지스",
  "트레인테크놀로지스",
  "티씨케이",
  "티에스이",
  "티엘비",
  "티엠씨",
  "파라다이스",
  "파미셀",
  "팔란티어",
  "팬오션",
  "퍼미",
  "펄어비스",
  "페트로브라스",
  "포스코",
  "포스코인터네셔널",
  "포스코DX",
  "폭스콘",
  "풍산",
  "프리포트맥모란",
  "플래닛랩스",
  "피제이메탈",
  "하나마이크론",
  "하모닉",
  "하모닉드라이브",
  "하이브",
  "한국우주항공",
  "한국전력",
  "한국카본",
  "한국투자증권",
  "한국피아이엠",
  "한국항공우주",
  "한미반도체",
  "한솔케미칼",
  "한수원",
  "한양디지텍",
  "한일현대시멘트",
  "한전기술",
  "한진",
  "한진칼",
  "한텍",
  "한화",
  "한화솔루션",
  "한화시스템",
  "한화에어로스페이스",
  "한화엔진",
  "한화오션",
  "할리버튼",
  "헌팅턴잉걸스",
  "헤사이",
  "헬리온에너지",
  "현대건설",
  "현대글로비스",
  "현대로템",
  "현대자동차",
  "호반",
  "홈플러스",
  "화웨이",
  "효성중공업",
  "후성",
  "히타치",
] as const;

// ─────────────────────────────────────────────
// 기준 Topic 태그 목록 (v8, 260개)
// ─────────────────────────────────────────────
export const CANONICAL_TOPICS = [
  "ADR",
  "AI",
  "AI공부",
  "AP",
  "ASIC",
  "C14",
  "CASK",
  "CBDC",
  "CCL",
  "CDN",
  "CDS",
  "CMOS",
  "CPO",
  "CPU",
  "CPX",
  "CSP",
  "DART",
  "DAS",
  "DDI",
  "DDR4",
  "DDR5",
  "DRAM",
  "DUV",
  "EPC",
  "ESS",
  "ETF",
  "EU",
  "EUV",
  "eVTOL",
  "FC-BGA",
  "FLNG",
  "GDDR",
  "GLP",
  "GPU",
  "HALEU",
  "HBF",
  "HBM",
  "HBS",
  "HDD",
  "HPC",
  "HVAC",
  "HVDC",
  "HVDC변압기",
  "IDM",
  "IPO",
  "ISA",
  "LCC",
  "LNG",
  "LNG가스제어시스템",
  "LNG저장탱크",
  "LNG터미널",
  "LNG플랜트",
  "LNG화물창",
  "LPDDR",
  "LPG",
  "LPU",
  "LTA",
  "M&A",
  "MBS",
  "MLCC",
  "MMR",
  "MRO",
  "NAND",
  "NDF",
  "NPU",
  "OCS",
  "ODM",
  "OEM",
  "OSAT",
  "PCB",
  "PE",
  "PF",
  "POSCAP",
  "PSU",
  "QLC",
  "RDL",
  "Report",
  "RWS",
  "SAAS",
  "SIC",
  "SMR",
  "SOC",
  "SOCAMM",
  "SOFC",
  "SRAM",
  "SSD",
  "STO",
  "TC본더",
  "TGV",
  "TLC",
  "TPU",
  "Trend",
  "UFS",
  "VC",
  "Youtube",
  "News",
  "가상자산",
  "가스터빈",
  "가전",
  "감속기",
  "거래소",
  "건강",
  "건설",
  "검사장비",
  "게임",
  "계측기",
  "골판지",
  "광네트워크",
  "광섬유",
  "광케이블",
  "광통신",
  "광통신부품",
  "광트랜시버",
  "광학",
  "광학반도체",
  "구리",
  "구조조정",
  "국장",
  "군함",
  "그리드",
  "규제",
  "금",
  "기뢰",
  "기판",
  "나프타",
  "냉각",
  "네오디뮴",
  "네오클라우드",
  "네트워킹",
  "네트워크백본인프라",
  "노광",
  "단조",
  "담배",
  "담수화플랜트",
  "데이터센터",
  "데크하우스",
  "드론",
  "디지털증권",
  "라이다",
  "라텍스",
  "래거시DRAM",
  "레이더",
  "레이저",
  "레이저마커",
  "레이저모듈",
  "레이저어닐링",
  "로봇",
  "로봇소부장",
  "로직다이",
  "리튬",
  "멀티클라우드",
  "메모리",
  "모듈러주택",
  "모바일기기",
  "모터",
  "몰리브덴",
  "물류",
  "미국",
  "미디어",
  "미사일",
  "미용의료",
  "바이오",
  "반도체",
  "반도체검사장비",
  "반도체기판",
  "반도체소부장",
  "반도체소재",
  "반도체이송시스템",
  "반도체장비",
  "반도체코어",
  "반도체패키징",
  "발견",
  "발사체",
  "방산",
  "배터리",
  "백화점",
  "밸류에이션",
  "밸류체인",
  "변압기",
  "보일러",
  "보험",
  "부채",
  "북극항",
  "분산안테나시스템",
  "비료",
  "비메모리",
  "빅테크",
  "사모대출",
  "사모펀드",
  "사용후핵연료",
  "산화알루미늄",
  "삼중수소",
  "서버",
  "서버OEM",
  "서비스",
  "석유화학",
  "석탄",
  "선박엔진",
  "선박크레인",
  "세금",
  "셰일",
  "소듐이온전지",
  "소매업",
  "소부장",
  "소비재",
  "소재",
  "소프트웨어",
  "수급",
  "수소",
  "수주공시",
  "스마트폰",
  "스타링크",
  "스테이블코인",
  "스팀터빈",
  "시멘트",
  "시장",
  "시추",
  "식각공정",
  "식량",
  "식수",
  "식음료",
  "식품",
  "신재생",
  "실리콘커패시터",
  "실리콘포토닉스",
  "실적",
  "심해채굴",
  "아연",
  "알루미늄",
  "암모니아",
  "암호화폐",
  "액체냉각",
  "액추에이터",
  "양극재",
  "양자컴퓨터",
  "에너지",
  "에너지인프라",
  "엔진",
  "엔터",
  "연금",
  "영구자석",
  "영화",
  "오일샌드",
  "완구",
  "요소",
  "요식업",
  "우라늄",
  "우주데이터센터",
  "우주항공",
  "운송",
  "원유",
  "원자재",
  "원전",
  "원전기자재",
  "유리기판",
  "유리섬유",
  "유전",
  "유틸리티",
  "은",
  "은행",
  "의류",
  "이벤트",
  "이차전지",
  "인공위성",
  "인도",
  "인도네시아",
  "인프라",
  "일본",
  "일차전지",
  "자동차",
  "자동차부품",
  "자율주행",
  "잠수함",
  "장기공급계약",
  "장기공급계약(LTA)",
  "재활용",
  "저궤도위성",
  "저장용기",
  "전고체",
  "전공정",
  "전구체",
  "전기차",
  "전력",
  "전력기기",
  "전력모듈",
  "전력반도체",
  "전쟁",
  "전차",
  "전투기",
  "전해알루미늄",
  "전해질",
  "정유",
  "정제",
  "정책",
  "제지",
  "조선",
  "조선기자재",
  "주주환원",
  "중국",
  "증권",
  "증설",
  "증착공정",
  "지분",
  "지분공시",
  "지주사",
  "지표",
  "차량용반도체",
  "천연가스",
  "철강",
  "철광석",
  "총알",
  "칩",
  "카지노",
  "캐스크",
  "컨트롤러",
  "케이블",
  "코스피",
  "코어",
  "클라우드",
  "태양광",
  "텅스텐",
  "테스트",
  "토륨원전",
  "통신",
  "통신망",
  "통신장비",
  "투자전략",
  "특수가스",
  "파운드리",
  "팜유",
  "패키징",
  "펠리클",
  "펨토초그루빙",
  "포장재",
  "포커스링",
  "포토레지스트",
  "포토마스크",
  "풍력",
  "프로브카드",
  "플랜트기자재",
  "플루토늄",
  "피팅",
  "하이브리드본더",
  "하이퍼스케일러",
  "한국",
  "합금",
  "항공",
  "항공기엔진",
  "해양플랜트",
  "해운",
  "해저케이블",
  "핵연료",
  "핵융합",
  "헤지펀드",
  "헬륨",
  "헬스케어",
  "호주",
  "화력발전",
  "화장품",
  "후공정",
  "휴머노이드",
  "희토류",
] as const;

// ─────────────────────────────────────────────
// 기준 Macro 태그 목록 — top-down 매크로·경제 지표 (Topic과 분리된 3번째 카테고리)
// ─────────────────────────────────────────────
export const CANONICAL_MACRO = [
  "금리",
  "기준금리",
  "국채",
  "채권",
  "회사채",
  "물가",
  "인플레이션",
  "디플레이션",
  "스태그플레이션",
  "CPI",
  "PPI",
  "PCE",
  "통화량",
  "유동성",
  "환율",
  "달러",
  "엔화",
  "위안화",
  "유로화",
  "유가",
  "WTI",
  "브렌트유",
  "연준",
  "FOMC",
  "한국은행",
  "ECB",
  "BOJ",
  "기축통화",
  "GDP",
  "경기침체",
  "실업률",
  "고용",
  "비농업",
  "무역",
  "무역수지",
  "경상수지",
  "관세",
  "무역분쟁",
  "수출",
  "지정학",
  "양적긴축",
  "양적완화",
  "소매판매",
  "PMI",
  "ISM",
  "생산",
  "부동산",
  "소비",
] as const;

// ─────────────────────────────────────────────
// 동의어 → 표준 태그 매핑 (소문자·공백제거 키 기준)
// C(동의어 통일), A(표기 형식), D(개별 예외) 규칙 반영
// ─────────────────────────────────────────────
const TOPIC_SYNONYMS: Record<string, string> = {
  "d램": "DRAM",
  "낸드": "NAND",
  "2차전지": "이차전지",
  "전기자동차": "전기차",
  "재생에너지": "신재생",
  "감광액": "포토레지스트",
  "박막증착": "증착공정",
  "프리커서": "전구체",
  "하이브리드본딩": "하이브리드본더",
  "양자컴퓨팅": "양자컴퓨터",
  "항공우주": "우주항공",
  "궤도데이터센터": "우주데이터센터",
  "sic링": "포커스링",
  "lpddr5x": "LPDDR",
  "hbm3e": "HBM",
  "인공지능": "AI",
  "메모리반도체": "메모리",
  "2차전지소재": "이차전지",
  "1차전지": "일차전지",
  "원자력": "원전",
  "정부정책": "정책",
  "환율정책": "정책",
  "휴머노이드로봇": "휴머노이드",
  "데이타센터": "데이터센터",
  "레거시dram": "래거시DRAM",
  "웨이퍼": "반도체소부장",
  "hvac공조": "HVAC",
  "saas": "SAAS",
  "코워스": "패키징",
  "반도체장비": "반도체소부장",
  "반도체소재": "반도체소부장",
  "반도체기판": "기판",
  "배터리": "이차전지",
  "cowos": "반도체패키징",
  "plp": "반도체패키징",
  "시스템반도체": "비메모리",
  "실리콘웨이퍼": "반도체소부장",
  "반도체검사장비": "반도체소부장",
  "액츄에이터": "액추에이터",
  "엔터테인먼트": "엔터",
  "지주회사": "지주사",
  "나트륨이온배터리": "소듐이온전지",
  "해상데이터센터": "데이터센터",
  "일본경제": "일본",
  "수출입": "수출",
  "소비심리": "소비",
  "해운업황": "해운",
  "기업실적": "실적",
  "실적분석": "실적",
  "신작게임": "게임",
  "캐주얼게임": "게임",
  "광학솔루션": "광학",
  "탄소규제": "규제",
  "금융규제": "규제",
  "총량규제": "규제",
  "레버리지etf": "ETF",
  "gpuaas": "GPU",
  "서버랙": "서버",
  "양자": "양자컴퓨터",
  "모바일": "모바일기기",
  "네트워크": "네트워킹",
  "사업구조조정": "구조조정",
  "퇴직연금": "연금",
  "수냉식냉각": "냉각",
  "장기공급계약": "LTA",
  "장기공급계약(lta)": "LTA",
};

// ─────────────────────────────────────────────
// Macro 동의어 → 표준 매크로 태그 매핑
// ─────────────────────────────────────────────
const MACRO_SYNONYMS: Record<string, string> = {
  "국제유가": "유가",
  "원유": "유가",
  "미국국채": "국채",
  "채권금리": "채권",
  "국채금리": "국채",
  "회사채발행": "회사채",
  "회사채금리": "회사채",
  "지정학적리스크": "지정학",
  "지정학적 리스크": "지정학",
  "주택/부동산": "부동산",
  "부동산대책": "부동산",
  "소비심리": "소비",
  "민간소비": "소비",
  "고용지표": "고용",
  "실업": "실업률",
  "제조업/pmi": "PMI",
  "소비자물가지수": "CPI",
  "소비자물가": "물가",
  "생산자물가": "물가",
  "생산자물가지수": "PPI",
  "개인소비지출": "PCE",
  "원달러환율": "환율",
  "원/달러": "환율",
  "외환": "환율",
  "인플레": "인플레이션",
  "인플레율": "인플레이션",
  "디플레": "디플레이션",
  "스태그": "스태그플레이션",
  "한은": "한국은행",
  "연방준비": "연준",
  "fed": "연준",
  "feds": "연준",
  "us달러": "달러",
  "usd": "달러",
  "미국달러": "달러",
  "엔": "엔화",
  "jpy": "엔화",
  "위안": "위안화",
  "cny": "위안화",
  "유로": "유로화",
  "eur": "유로화",
  "금리인상": "금리",
  "금리인하": "금리",
  "기준금리인상": "기준금리",
  "기준금리인하": "기준금리",
  "qt": "양적긴축",
  "qe": "양적완화",
  "소매": "소매판매",
  "산업생산": "생산",
  "경기": "경기침체",
  "리세션": "경기침체",
};

const COMPANY_SYNONYMS: Record<string, string> = {
  "앤스로픽": "엔트로픽",
  "wd": "웨스턴디지털",
  "openai": "오픈AI",
  "google": "구글",
  "amazon": "아마존",
  "meta": "메타",
  "apple": "애플",
  "nvidia": "엔비디아",
  "microsoft": "마이크로소프트",
  "tesla": "테슬라",
  "intel": "인텔",
  "qualcomm": "퀄컴",
  "broadcom": "브로드컴",
  "micron": "마이크론",
  "kioxia": "키옥시아",
  "sandisk": "샌디스크",
  "spacex": "스페이스X",
  "oracle": "오라클",
  "netflix": "넷플릭스",
  "dell": "DELL",
  "coreweave": "코어위브",
  "coinbase": "코인베이스",
  "palantir": "팔란티어",
  "vertiv": "버티브홀딩스",
  "eaton": "이튼",
  "marvell": "마벨테크놀로지",
  "lumentum": "루멘텀",
  "coherent": "코히어런트",
  "arista": "아리스타네트웍스",
  "supermicro": "슈퍼마이크로컴퓨터",
  "eli lilly": "일라이릴리",
  "cameco": "카메코",
  "rocketlab": "로켓랩",
  "lockheedmartin": "록히드마틴",
  "siemens": "지멘스",
  "지맨스에너지": "지멘스에너지",
  "gevernova": "GE버노바",
  "carrier": "캐리어",
  "quanta": "콴타",
  "foxconn": "폭스콘",
  "huawei": "화웨이",
  "tencent": "텐센트",
  "alibaba": "알리바바",
  "baidu": "바이두",
  "posco": "포스코",
  "포스코홀딩스": "포스코",
  "현대중공업": "HD현대중공업",
  "현대일렉트릭": "HD현대일렉트릭",
  "현대오일뱅크": "HD현대오일뱅크",
  "현대에너지솔루션": "HD현대에너지솔루션",
  "s-oil": "에쓰오일",
  "미래에셋": "미래에셋증권",
  "한화에어로": "한화에어로스페이스",
  "한국항공우주산업": "한국항공우주",
  "넥스원": "LIG넥스원",
  "삼성sdi": "삼성SDI",
  "삼성sds": "삼성SDS",
  "삼성엔지니어링": "삼성E&A",
  "sk하이닉스": "SK하이닉스",
  "현대차": "현대자동차",
  "kt&g": "KTNG",
  "$mpwr": "Monolithic",
  "$nvts": "나비타스세미컨덕터",
  "$vicr": "Vicor",
  "$etn": "이튼",
  "$litn": "루멘텀",
  "$cohr": "코히어런트",
  "$ccj": "카메코",
  "amkor": "Amkor",
  "alphabet": "구글",
  "ast스페이스모바일": "AST스페이스모바일",
  "asts": "ASTS",
  "현대차그룹": "현대자동차",
  "코히런트": "코히어런트",
  "바이코": "Vicor",
  "닉스": "SK하이닉스",
  "oci홀딩스": "OCI",
  "세아베스틸": "세아베스틸지주",
  "난야": "난야테크놀로지",
  "키오시아": "키옥시아",
  "jp모건체이스": "JP모건",
  "한국전력공사": "한국전력",
  "lselectric": "LS일렉트릭",
  "시게이트": "씨게이트",
  "펭귄솔루션즈": "펭귄솔루션스",
  "에스테팜": "에스티팜",
  "브이엠": "제이브이엠",
  "피에스케이홀딩스": "피에스케이",
  "마이크론테크놀로지": "마이크론",
};

// ─────────────────────────────────────────────
// 정규화 로직
// ─────────────────────────────────────────────
const canonicalTopicByKey = new Map<string, string>();
for (const t of CANONICAL_TOPICS) canonicalTopicByKey.set(normKey(t), t);
const canonicalCompanyByKey = new Map<string, string>();
for (const c of CANONICAL_COMPANIES) canonicalCompanyByKey.set(normKey(c), c);
const canonicalMacroByKey = new Map<string, string>();
for (const m of CANONICAL_MACRO) canonicalMacroByKey.set(normKey(m), m);

// 카테고리 간 상호 배타 보장 — 다른 카테고리의 기준 태그와 정확히 일치하면 해당 카테고리에는 저장하지 않는다
// (LLM이 TAG_RULES_PROMPT의 카테고리 지침을 무시하고 예: "채권"을 topics에 넣어도 여기서 걸러진다)
const macroOrCompanyByKey = new Map<string, string>([...canonicalMacroByKey, ...canonicalCompanyByKey]);
const topicOrMacroByKey = new Map<string, string>([...canonicalTopicByKey, ...canonicalMacroByKey]);
const topicOrCompanyByKey = new Map<string, string>([...canonicalTopicByKey, ...canonicalCompanyByKey]);

// 분류 목적에 부합하지 않는 태그 — 카테고리 불문 자동 태깅 차단 (기존 저장분은 별도 정리 스크립트로 제거)
const BLOCKED_TAG_KEYS = new Set(["매크로", "한국주식"].map(normKey));

/** 비교용 키: 소문자화 + 공백 제거 (A-3/A-4 띄어쓰기 없는 버전 매칭) */
function normKey(s: string): string {
  return s.toLowerCase().replace(/\s+/g, "");
}

/** A-5/A-6/A-11/A-12: 표기 형식 정리 — #제거, ($티커)/괄호 티커 제거, "한글명(약어)" → 약어 판단은 매핑에 위임 */
function cleanFormat(raw: string): string {
  let s = raw.trim();
  s = s.replace(/^#+/, "");                      // A-12 해시태그 제거
  s = s.replace(/\(\$?[A-Z]{1,6}\)\s*$/i, "");   // A-6 뒤에 붙은 (티커)/($티커) 제거
  s = s.replace(/\s{2,}/g, " ").trim();
  return s;
}

function resolve(
  raw: string,
  synonyms: Record<string, string>,
  canonicalByKey: Map<string, string>,
  excludeByKey?: Map<string, string>,
): string | null {
  const cleaned = cleanFormat(raw);
  if (!cleaned) return null;
  const key = normKey(cleaned);
  if (BLOCKED_TAG_KEYS.has(key)) return null;

  let resolved: string;
  // 1) 동의어 매핑 우선
  if (synonyms[key]) {
    resolved = synonyms[key];
  } else {
    // 2) 기준 목록과 일치 (대소문자·공백 무시)
    const canonical = canonicalByKey.get(key);
    if (canonical) {
      resolved = canonical;
    } else {
      // 3) 기준 목록에 없으면 신규 태그로 유지 — 단 B-1/B-2 문장형·구조용 태그는 폐기한다
      //    (15자 초과, 문장부호 포함, 또는 띄어쓰기 포함 시 문장/구절로 보고 통째로 버림 —
      //    공백만 지우고 살리면 "실적 분석"→"실적분석" 같은 저품질 신규 태그가 계속 쌓이므로
      //    A-3/A-4 띄어쓰기 없는 표기 규칙은 기준 목록·동의어 일치분에만 적용하고 자유입력에는 적용하지 않는다)
      if (cleaned.length > 15 || /[.,!?"'…]/.test(cleaned) || /\s/.test(cleaned)) return null;
      resolved = cleaned;
    }
  }

  const resolvedKey = normKey(resolved);
  if (BLOCKED_TAG_KEYS.has(resolvedKey)) return null;
  // 다른 카테고리의 기준 태그와 정확히 일치하면 이 카테고리에는 남기지 않는다
  if (excludeByKey?.has(resolvedKey)) return null;
  return resolved;
}

/** Topic 태그 배열 정규화: 동의어 통일 + 형식 정리 + 중복 제거 */
export function normalizeTopics(tags: string[]): string[] {
  const out: string[] = [];
  for (const t of tags) {
    const r = resolve(String(t ?? ""), TOPIC_SYNONYMS, canonicalTopicByKey, macroOrCompanyByKey);
    if (r && !out.includes(r)) out.push(r);
  }
  return out;
}

/** Macro 태그 배열 정규화: 동의어 통일 + 형식 정리 + 중복 제거 */
export function normalizeMacro(tags: string[]): string[] {
  const out: string[] = [];
  for (const t of tags) {
    const r = resolve(String(t ?? ""), MACRO_SYNONYMS, canonicalMacroByKey, topicOrCompanyByKey);
    if (r && !out.includes(r)) out.push(r);
  }

  // CPI가 포함되면 물가도 자동 추가
  if (out.includes("CPI") && !out.includes("물가")) {
    out.push("물가");
  }
  // 달러가 포함되면 환율도 자동 추가
  if (out.includes("달러") && !out.includes("환율")) {
    out.push("환율");
  }

  return out;
}

/** Company 태그 배열 정규화: 동의어 통일 + 형식 정리 + 중복 제거 + D-4(SK 지주사) 처리 */
export function normalizeCompanies(tags: string[]): string[] {
  const out: string[] = [];
  for (const t of tags) {
    const r = resolve(String(t ?? ""), COMPANY_SYNONYMS, canonicalCompanyByKey, topicOrMacroByKey);
    if (r && !out.includes(r)) out.push(r);
  }
  // D-4: SK 계열사 태그가 함께 있으면 지주사 'SK' 제거
  const skAffiliates = ["SK하이닉스", "SK이노베이션", "SK텔레콤", "SK가스", "SKC"];
  if (out.includes("SK") && out.some((c) => skAffiliates.includes(c))) {
    return out.filter((c) => c !== "SK");
  }
  return out;
}

function containsTagMention(text: string, candidate: string): boolean {
  const compactText = text.toLowerCase().replace(/[^0-9a-z가-힣]/g, "");
  const compactCandidate = candidate.toLowerCase().replace(/[^0-9a-z가-힣]/g, "");
  if (!compactCandidate) return false;

  if (/^[가-힣]$/.test(candidate)) {
    const escaped = candidate.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&");
    return new RegExp(`(^|[^0-9a-z가-힣])${escaped}([^0-9a-z가-힣]|$)`, "i").test(text);
  }
  if (/^[a-z0-9]+$/i.test(candidate) && compactCandidate.length <= 3) {
    const escaped = candidate.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&");
    return new RegExp(`(^|[^a-z0-9])${escaped}([^a-z0-9]|$)`, "i").test(text);
  }
  return compactText.includes(compactCandidate);
}

function mentionedTags(
  text: string,
  canonical: readonly string[],
  synonyms: Record<string, string>,
): string[] {
  return [
    ...canonical.filter((tag) => containsTagMention(text, tag)),
    ...Object.keys(synonyms).filter((tag) => containsTagMention(text, tag)),
  ];
}

/**
 * AI 태그가 아직 저장되지 않은 목록/레거시 행을 위한 결정적 폴백 추출.
 * 기준 태그뿐 아니라 동의어 키도 함께 탐색한 뒤 기존 정규화 규칙을 그대로 적용한다.
 */
export function extractMappedTags(text: string): {
  topics: string[];
  companies: string[];
  macro: string[];
} {
  return {
    topics: normalizeTopics(mentionedTags(text, CANONICAL_TOPICS, TOPIC_SYNONYMS)),
    companies: normalizeCompanies(mentionedTags(text, CANONICAL_COMPANIES, COMPANY_SYNONYMS)),
    macro: normalizeMacro(mentionedTags(text, CANONICAL_MACRO, MACRO_SYNONYMS)),
  };
}

// ─────────────────────────────────────────────
// 프롬프트용 규칙 블록 (LLM에 지시)
// ─────────────────────────────────────────────
export const TAG_RULES_PROMPT = `[태그 표기 규칙 — 반드시 준수]
1. 아래 "기준 태그 목록"에 있는 표기를 최우선으로 사용. 의미가 같으면 반드시 목록의 표기를 그대로 사용 (예: D램 → DRAM, 2차전지 → 이차전지, EV → 전기차).
2. 회사명은 한글 정식 명칭 사용: 엔비디아(NVIDIA X), 오픈AI(OpenAI X), 구글(Google/Alphabet X), 마이크로소프트(MS X), 아마존(AWS X), 테슬라, 메타, 애플, 인텔, 브로드컴, 마이크론. 단 기준 목록에 영문으로 등재된 것(TSMC, AMD, ARM, CATL, BYD, DELL 등)은 그 영문 표기 유지.
3. 띄어쓰기 없는 표기 사용: "전력 반도체" X → "전력반도체", "GE 버노바" X → "GE버노바".
4. 티커·해시태그·괄호 설명 금지: "이튼($ETN)" X → "이튼", "동박적층판(CCL)" X → "CCL".
5. 규격의 세부 버전 대신 공통 규격: LPDDR5X X → LPDDR, HBM3E/HBM4 X → HBM.
6. 사명 변경 반영: 현대중공업 X → HD현대중공업. 지주사·사업부 대신 대표 회사명: 포스코홀딩스 X → 포스코, AWS X → 아마존.
7. 문장·메모·분류용 태그 금지 (태그는 명사형 고유명사/테마만).
8. SK 계열사(SK하이닉스 등)를 태그했다면 지주사 'SK'는 함께 넣지 않는다.
9. 앤스로픽 X → 엔트로픽, WD X → 웨스턴디지털, SIC링 X → 포커스링, 항공우주 X → 우주항공, 양자컴퓨팅 X → 양자컴퓨터.
10. 목록에 없는 새로운 개념일 때만 새 태그 생성 가능 — 이때도 위 형식 규칙(한글 우선·띄어쓰기 없음·명사형)을 지킨다.
11. 단순히 스치듯 한 번 언급되거나, 비교군/경쟁사 등으로 나열만 된 기업은 태그에서 제외한다. 본문의 주된 주제이거나 중심 내용으로서 비중 있게 다뤄진 핵심 기업만 Company 태그로 포함한다.
12. Topic과 별도로 Macro 태그를 매긴다. 금리·물가·환율·유가·GDP·고용·무역·관세·지정학·부동산·소비 같은 top-down 매크로·경제 지표는 Topic이 아니라 Macro 목록에서 선택한다 (예: "금리 인상" 기사 → Topic이 아니라 Macro에 "금리". 산업/기업 고유 테마는 여전히 Topic).
13. "매크로", "한국주식" 처럼 그 자체로 아무 것도 구분해주지 못하는 포괄적·자기지시적 태그는 절대 사용하지 않는다 — 반드시 구체적인 지표/테마/기업명으로 태그한다.
14. 태그는 본문(전문·자막·PDF) 내용을 기준으로 판단한다. 제목에도 동일한 개념이 등장하면 본문에서도 핵심적으로 다뤄졌을 가능성이 높으므로 그 태그의 채택 우선순위를 더 높게 준다.`;

/** 프롬프트에 삽입할 기준 태그 목록 힌트 (토큰 절약을 위해 필요 시 사용) */
export function buildTagListHint(): string {
  return `기준 Topic 태그 목록: ${CANONICAL_TOPICS.join(", ")}\n기준 Company 태그 목록: ${CANONICAL_COMPANIES.join(", ")}\n기준 Macro 태그 목록: ${CANONICAL_MACRO.join(", ")}`;
}

/** 본문 내용에 포함된 기준 태그들만 추출해 프롬프트 힌트로 주입 (토큰 절약 및 속도 향상) */
export function buildDynamicTagListHint(title: string, content: string): string {
  const haystack = (String(title ?? "") + " " + String(content ?? "")).toLowerCase().replace(/\s+/g, "");
  
  // 소문자 및 공백 제거 기준으로 비교하여 포함 여부 판단
  const matchedTopics = CANONICAL_TOPICS.filter((t) => haystack.includes(t.toLowerCase().replace(/\s+/g, "")));
  const matchedCompanies = CANONICAL_COMPANIES.filter((c) => haystack.includes(c.toLowerCase().replace(/\s+/g, "")));
  const matchedMacro = CANONICAL_MACRO.filter((m) => haystack.includes(m.toLowerCase().replace(/\s+/g, "")));
  
  return `기준 Topic 태그 목록: ${matchedTopics.join(", ")}\n기준 Company 태그 목록: ${matchedCompanies.join(", ")}\n기준 Macro 태그 목록: ${matchedMacro.join(", ")}`;
}


