import { NextRequest,NextResponse } from "next/server";
import { formatSupabaseError,getInsightSupabase,insightDbUnavailable } from "@/lib/supabaseInsightDb";
import type { TagType } from "@/app/analysis/integratedInsight/insightAggregates";
export type CitationSource={source:string;title:string;summary:string;date:string;url?:string|null};
export type DebateLogRow={id:number;keyword:string;tagType:TagType;itemCount:number;dateFrom:string|null;dateTo:string|null;bullOpening:string;bearOpening:string;bullRebuttal:string;bearRebuttal:string;verdict:string;rationale:string;watchpoints:string;confidence:string;sourceItems:CitationSource[];createdAt:string};
export type DebateResult=Omit<DebateLogRow,"id"|"createdAt">;
const mapRow=(r:Record<string,unknown>):DebateLogRow=>({id:Number(r.id),keyword:String(r.keyword??""),tagType:String(r.tag_type??"theme") as TagType,itemCount:Number(r.item_count??0),dateFrom:r.date_from?String(r.date_from):null,dateTo:r.date_to?String(r.date_to):null,bullOpening:String(r.bull_opening??""),bearOpening:String(r.bear_opening??""),bullRebuttal:String(r.bull_rebuttal??""),bearRebuttal:String(r.bear_rebuttal??""),verdict:String(r.verdict??""),rationale:String(r.rationale??""),watchpoints:String(r.watchpoints??""),confidence:String(r.confidence??""),sourceItems:Array.isArray(r.source_items)?r.source_items as CitationSource[]:[],createdAt:String(r.created_at??"")});
export async function GET(req:NextRequest){const db=getInsightSupabase(req);if(!db)return NextResponse.json(insightDbUnavailable(),{status:401});const limit=Math.min(200,Math.max(1,Number(req.nextUrl.searchParams.get("limit")??50)||50));let q=db.from("insight_debate_log").select("id,keyword,tag_type,item_count,date_from,date_to,bull_opening,bear_opening,bull_rebuttal,bear_rebuttal,verdict,rationale,watchpoints,confidence,source_items,created_at").order("created_at",{ascending:false}).limit(limit);const keyword=req.nextUrl.searchParams.get("keyword");if(keyword)q=q.ilike("keyword",`%${keyword}%`);const {data,error}=await q;return error?NextResponse.json({error:formatSupabaseError(error)},{status:500}):NextResponse.json({debates:(data??[]).map(r=>mapRow(r as Record<string,unknown>))});}
export async function DELETE(req:NextRequest){const db=getInsightSupabase(req);if(!db)return NextResponse.json(insightDbUnavailable(),{status:401});const id=Number(req.nextUrl.searchParams.get("id"));if(!Number.isFinite(id))return NextResponse.json({error:"id가 필요합니다."},{status:400});const {error}=await db.from("insight_debate_log").delete().eq("id",id);return error?NextResponse.json({error:formatSupabaseError(error)},{status:500}):NextResponse.json({success:true});}
export async function POST(req:NextRequest){const db=getInsightSupabase(req);if(!db)return NextResponse.json(insightDbUnavailable(),{status:401});const {keyword:raw}=await req.json() as {keyword?:string};const keyword=(raw??"").trim();if(!keyword)return NextResponse.json({error:"keyword가 필요합니다."},{status:400});const tables=[
  ["유튜브","youtube_summaries","title,summary,date,video_url,topics,companies,macro"],["블로그","blog_summaries","title,summary,date,post_url,topics,companies,macro"],["텔레그램","telegram_saved","text,summary,msg_date,link,topic_tags,company_tags,macro_tags"],["뉴스","news_articles","title,notes,published_date,url,topic_tags,company_tags,macro_tags"],["리포트","report_db","title,ai_summary,published_date,url,topic_tags,company_tags,macro_tags"]
] as const;const sources:CitationSource[]=[];for(const [label,table,columns] of tables){const {data}=await db.from(table).select(columns).limit(300);for(const row of data??[]){const values=Object.values(row as Record<string,unknown>).flat().join(" ");if(!values.toLowerCase().includes(keyword.toLowerCase()))continue;const r=row as Record<string,unknown>;sources.push({source:label,title:String(r.title??r.text??"").slice(0,120),summary:String(r.summary??r.notes??r.ai_summary??"").slice(0,500),date:String(r.date??r.msg_date??r.published_date??"").slice(0,10),url:String(r.video_url??r.post_url??r.link??r.url??"")||null});}}if(!sources.length)return NextResponse.json({error:"이 키워드로 저장된 자료가 없습니다."},{status:400});const selected=sources.slice(0,40);const positive=selected.filter(source=>/증가|상승|성장|개선|호조|수주|확대/.test(source.title+" "+source.summary));const negative=selected.filter(source=>/감소|하락|둔화|악화|리스크|규제|부진/.test(source.title+" "+source.summary));const cite=(rows:CitationSource[])=>rows.slice(0,4).map(row=>`${row.title}(${row.source}, ${row.date})`).join(" · ")||"뚜렷한 근거가 부족합니다.";const result:DebateResult={keyword,tagType:"theme",itemCount:sources.length,dateFrom:selected.map(s=>s.date).filter(Boolean).sort()[0]??null,dateTo:selected.map(s=>s.date).filter(Boolean).sort().at(-1)??null,bullOpening:`강세 관점에서는 긍정 신호가 확인된 자료를 우선 근거로 봅니다. ${cite(positive)}`,bearOpening:`약세 관점에서는 하방 위험이 언급된 자료를 우선 점검합니다. ${cite(negative)}`,bullRebuttal:negative.length?"부정적 신호가 존재하지만 최신 긍정 자료가 일시적 위험인지 구조적 변화인지 구분해야 합니다.":"현재 저장 자료에서는 강한 반대 근거가 제한적입니다.",bearRebuttal:positive.length?"긍정적 신호가 실제 실적과 가격에 이미 반영됐는지 확인해야 합니다.":"현재 저장 자료에서는 강한 상승 근거가 제한적입니다.",verdict:positive.length>negative.length?"강세 우위":negative.length>positive.length?"약세 우위":"팽팽함",rationale:`긍정 신호 ${positive.length}건과 부정 신호 ${negative.length}건을 비교했습니다. 저장 자료의 방향성만 반영한 결과이므로 원문과 최신 시장 데이터를 함께 확인해야 합니다.`,watchpoints:"후속 실적·공시·거시지표가 기존 방향성을 강화하거나 반전시키는지 확인하세요.",confidence:selected.length>=10?"중간":"낮음",sourceItems:selected};const {error}=await db.from("insight_debate_log").insert({keyword:result.keyword,tag_type:result.tagType,item_count:result.itemCount,date_from:result.dateFrom,date_to:result.dateTo,bull_opening:result.bullOpening,bear_opening:result.bearOpening,bull_rebuttal:result.bullRebuttal,bear_rebuttal:result.bearRebuttal,verdict:result.verdict,rationale:result.rationale,watchpoints:result.watchpoints,confidence:result.confidence,source_items:result.sourceItems});if(error)return NextResponse.json({error:formatSupabaseError(error)},{status:500});return NextResponse.json(result);}
