import { NextRequest, NextResponse } from "next/server";
import { formatSupabaseError, getInsightSupabase, insightDbUnavailable } from "@/lib/supabaseInsightDb";
import { normalizeCompanies, normalizeMacro, normalizeTopics } from "@/lib/tagRules";

export type ReportCategory="company"|"industry"|"invest"|"economy";
export type ReportItem={title:string;category:ReportCategory;itemName:string;broker:string;date:string;pdfUrl:string|null;detailUrl:string};
const NAVER="https://finance.naver.com";
const listPath:Record<ReportCategory,string>={company:"company_list.naver",industry:"industry_list.naver",invest:"invest_list.naver",economy:"economy_list.naver"};
const headers={"User-Agent":"Mozilla/5.0","Accept-Language":"ko-KR,ko;q=0.9",Referer:NAVER};
const strip=(html:string)=>html.replace(/<br\s*\/?>/gi,"\n").replace(/<[^>]+>/g,"").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").trim();
const absolute=(value:string)=>{try{return new URL(value,NAVER).toString();}catch{return "";}};
async function html(url:string){const parsed=new URL(url);if(parsed.origin!==NAVER)throw new Error("허용되지 않은 리포트 주소입니다.");const response=await fetch(parsed,{headers,cache:"no-store"});if(!response.ok)return "";return new TextDecoder("euc-kr").decode(await response.arrayBuffer());}
function parseRows(source:string,category:ReportCategory):ReportItem[]{const out:ReportItem[]=[];for(const match of source.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){const cells=[...match[1].matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(v=>v[1]);const hasItem=category==="company"||category==="industry";const [item,titleCell,broker,pdf,date]=hasItem?[cells[0],cells[1],cells[2],cells[3],cells[4]]:["",cells[0],cells[1],cells[2],cells[3]];const anchor=titleCell?.match(/href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i);const dateText=strip(date??"");if(!anchor||!/^\d{2}\.\d{2}\.\d{2}$/.test(dateText))continue;const pdfMatch=pdf?.match(/href="([^"]+)"/i);out.push({title:strip(anchor[2]),category,itemName:strip(item??""),broker:strip(broker??""),date:dateText,pdfUrl:pdfMatch?absolute(pdfMatch[1]):null,detailUrl:absolute(anchor[1])});}return out;}

export async function GET(req:NextRequest){const action=req.nextUrl.searchParams.get("action")??"list";if(action==="detail"){const url=req.nextUrl.searchParams.get("url")??"";try{const source=await html(url);const match=source.match(/<td[^>]*class="view_cnt"[^>]*>([\s\S]*?)<\/td>/i);return NextResponse.json({text:strip(match?.[1]??""),targetPrice:"-",opinion:"-"});}catch(error){return NextResponse.json({error:String(error)},{status:400});}}
  const db=getInsightSupabase(req);if(!db)return NextResponse.json(insightDbUnavailable(),{status:401});
  if(action==="saved"){const {data,error}=await db.from("report_db").select("id,title,url,category,broker,item_name,published_date,pdf_url,ai_summary,original_text,topic_tags,company_tags,macro_tags,notes,created_at").order("created_at",{ascending:false}).limit(2000);return error?NextResponse.json({error:formatSupabaseError(error)},{status:500}):NextResponse.json({reports:data??[]});}
  const raw=req.nextUrl.searchParams.get("category") as ReportCategory|null;const category=raw&&raw in listPath?raw:"company";const page=Math.max(1,Number(req.nextUrl.searchParams.get("page")??1)||1);try{let reports=parseRows(await html(`${NAVER}/research/${listPath[category]}?page=${page}`),category);const keyword=(req.nextUrl.searchParams.get("keyword")??"").trim().toLowerCase();if(keyword)reports=reports.filter(r=>`${r.title} ${r.itemName} ${r.broker}`.toLowerCase().includes(keyword));return NextResponse.json({category,reports:reports.slice(0,60),page,hasMore:reports.length>0});}catch(error){return NextResponse.json({error:String(error)},{status:502});}}
export async function POST(req:NextRequest){const db=getInsightSupabase(req);if(!db)return NextResponse.json(insightDbUnavailable(),{status:401});const v=await req.json() as Record<string,unknown>;const row={title:String(v.title??""),url:String(v.url??""),category:String(v.category??"company"),broker:String(v.broker??""),item_name:String(v.item_name??""),published_date:v.published_date||null,pdf_url:v.pdf_url||null,ai_summary:String(v.ai_summary??""),original_text:String(v.original_text??"").slice(0,20000),topic_tags:normalizeTopics(Array.isArray(v.topic_tags)?v.topic_tags.map(String):[]),company_tags:normalizeCompanies(Array.isArray(v.company_tags)?v.company_tags.map(String):[]),macro_tags:normalizeMacro(Array.isArray(v.macro_tags)?v.macro_tags.map(String):[]),notes:String(v.notes??"")};if(!row.title||!row.url)return NextResponse.json({error:"제목과 URL이 필요합니다."},{status:400});const {data,error}=await db.from("report_db").upsert(row,{onConflict:"url"}).select().single();return error?NextResponse.json({error:formatSupabaseError(error)},{status:500}):NextResponse.json({report:data});}
export async function DELETE(req:NextRequest){const db=getInsightSupabase(req);if(!db)return NextResponse.json(insightDbUnavailable(),{status:401});const {id}=await req.json();const {error}=await db.from("report_db").delete().eq("id",String(id??""));return error?NextResponse.json({error:formatSupabaseError(error)},{status:500}):NextResponse.json({ok:true});}
