import type { DailyPrice } from './types'

export type ChartRow = DailyPrice & { sma20: number | null; ema12: number | null; support: number | null; resistance: number | null; tenkan: number | null; kijun: number | null; spanA: number | null; spanB: number | null; chikou: number | null }
const nullable = (n: number) => new Array<number | null>(n).fill(null)
export function sma(values: readonly number[], period: number) { const result = nullable(values.length); for (let i = period - 1; i < values.length; i++) result[i] = values.slice(i - period + 1, i + 1).reduce((a, b) => a + b, 0) / period; return result }
export function ema(values: readonly number[], period: number) { const result = nullable(values.length); if (values.length < period) return result; let current = values.slice(0, period).reduce((a,b) => a + b, 0) / period; result[period - 1] = current; const k = 2 / (period + 1); for (let i = period; i < values.length; i++) { current = values[i] * k + current * (1-k); result[i] = current } return result }
function midpoint(data: readonly DailyPrice[], period: number) { const out = nullable(data.length); for (let i = period - 1; i < data.length; i++) { const chunk = data.slice(i - period + 1, i + 1); out[i] = (Math.max(...chunk.map(x => x.high ?? x.close)) + Math.min(...chunk.map(x => x.low ?? x.close))) / 2 } return out }
function trend(data: readonly DailyPrice[], useHigh: boolean) { const out = nullable(data.length); const from = Math.max(0, data.length - 60); if (data.length - from < 10) return out; const points = data.slice(from).map((d,i) => ({ x: i + from, y: useHigh ? d.high ?? d.close : d.low ?? d.close })); const n = points.length; const sx = points.reduce((s,p) => s+p.x,0); const sy = points.reduce((s,p) => s+p.y,0); const sxy = points.reduce((s,p) => s+p.x*p.y,0); const sx2 = points.reduce((s,p) => s+p.x*p.x,0); const slope = (n*sxy-sx*sy)/(n*sx2-sx*sx); const intercept = (sy-slope*sx)/n; for (let i=from;i<data.length;i++) out[i] = slope*i+intercept; return out }
/** Pure-function adaptation of report-summation's SMA/EMA, trend, and Ichimoku midpoint calculations. */
export function withChartIndicators(data: readonly DailyPrice[]): ChartRow[] { const close=data.map(x=>x.close); const tenkan=midpoint(data,9); const kijun=midpoint(data,26); const spanB=midpoint(data,52); const spanA=tenkan.map((v,i)=>v!==null&&kijun[i]!==null?(v+kijun[i]!)/2:null); return data.map((item,i)=>({ ...item, sma20:sma(close,20)[i], ema12:ema(close,12)[i], support:trend(data,false)[i], resistance:trend(data,true)[i], tenkan:tenkan[i], kijun:kijun[i], spanA:spanA[i], spanB:spanB[i], chikou:i+26<close.length?close[i+26]:null })) }
